export const CONFIG_LOADED = 'CONFIG_LOADED';
export const RATES_LOADED = 'RATES_LOADED';
export const FILTER_CHANGED = 'FILTER_CHANGED';
export const FILTER_CLEARED = 'FILTER_CLEARED';
export const WATCH_TOGGLED = 'WATCH_TOGGLED';
export const WATCH_STARTED = 'WATCH_STARTED';
