import { DefaultTheme } from "styled-components";
import { baseTheme, colorPalette } from "./base-theme";

export const materialLightTheme: DefaultTheme = {
  ...baseTheme,
  colors: {
    ...baseTheme.colors,
    primary: {
      main: colorPalette.primary[40],
      on: colorPalette.primary[100],
      container: colorPalette.primary[90],
      onContainer: colorPalette.primary[10],
      fixed: colorPalette.primary[90],
      fixedDim: colorPalette.primary[80],
      onFixed: colorPalette.primary[10],
      onFixedVariant: colorPalette.primary[30],
    },
    secondary: {
      main: colorPalette.secondary[40],
      on: colorPalette.secondary[100],
      container: colorPalette.secondary[90],
      onContainer: colorPalette.secondary[10],
      fixed: colorPalette.secondary[90],
      fixedDim: colorPalette.secondary[80],
      onFixed: colorPalette.secondary[10],
      onFixedVariant: colorPalette.secondary[30],
    },
    tertiary: {
      main: colorPalette.tertiary[40],
      on: colorPalette.tertiary[100],
      container: colorPalette.tertiary[90],
      onContainer: colorPalette.tertiary[10],
      fixed: colorPalette.tertiary[90],
      fixedDim: colorPalette.tertiary[80],
      onFixed: colorPalette.tertiary[10],
      onFixedVariant: colorPalette.tertiary[30],
    },
    error: {
      main: colorPalette.error[40],
      on: colorPalette.error[100],
      container: colorPalette.error[90],
      onContainer: colorPalette.error[10],
    },
    surface: {
      main: colorPalette.neutral[100],
      on: colorPalette.neutral[20],
      variant: colorPalette.neutralVariant[90],
      onVariant: colorPalette.neutralVariant[30],
      inverse: colorPalette.neutral[20],
      inverseOn: colorPalette.neutral[95],
      tint: colorPalette.primary[40],
      containerHighest: colorPalette.neutral[90],
      containerHigh: colorPalette.neutral[92],
      container: colorPalette.neutral[94],
      containerLow: colorPalette.neutral[96],
      containerLowest: colorPalette.neutral[100],
      bright: colorPalette.neutral[98],
      dim: colorPalette.neutral[87],
    },
    outline: {
      main: colorPalette.neutralVariant[50],
      variant: colorPalette.neutralVariant[80],
    },
  },
};

export const materialDarkTheme: DefaultTheme = {
  ...baseTheme,
  colors: {
    ...baseTheme.colors,
    primary: {
      main: colorPalette.primary[80],
      on: colorPalette.primary[20],
      container: colorPalette.primary[30],
      onContainer: colorPalette.primary[90],
      fixedDim: colorPalette.primary[80],
      fixed: colorPalette.primary[90],
      onFixed: colorPalette.primary[10],
      onFixedVariant: colorPalette.primary[30],
    },
    secondary: {
      main: colorPalette.secondary[80],
      on: colorPalette.secondary[20],
      container: colorPalette.secondary[30],
      onContainer: colorPalette.secondary[90],
      fixedDim: colorPalette.secondary[80],
      fixed: colorPalette.secondary[90],
      onFixed: colorPalette.secondary[10],
      onFixedVariant: colorPalette.secondary[30],
    },
    tertiary: {
      main: colorPalette.tertiary[80],
      on: colorPalette.tertiary[20],
      container: colorPalette.tertiary[30],
      onContainer: colorPalette.tertiary[90],
      fixedDim: colorPalette.tertiary[80],
      fixed: colorPalette.tertiary[90],
      onFixed: colorPalette.tertiary[10],
      onFixedVariant: colorPalette.tertiary[30],
    },
    error: {
      main: colorPalette.error[80],
      on: colorPalette.error[20],
      container: colorPalette.error[30],
      onContainer: colorPalette.error[90],
    },
    surface: {
      main: colorPalette.neutral[6],
      on: colorPalette.neutral[95],
      variant: colorPalette.neutralVariant[30],
      onVariant: colorPalette.neutralVariant[80],
      inverse: colorPalette.neutral[90],
      inverseOn: colorPalette.neutral[20],
      tint: colorPalette.primary[80],
      containerHighest: colorPalette.neutral[22],
      containerHigh: colorPalette.neutral[17],
      container: colorPalette.neutral[12],
      containerLow: colorPalette.neutral[10],
      containerLowest: colorPalette.neutral[4],
      bright: colorPalette.neutral[24],
      dim: colorPalette.neutral[6],
    },
    outline: {
      main: colorPalette.neutralVariant[60],
      variant: colorPalette.neutralVariant[30],
    },
  },
};
