name: movie_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  http: ^0.13.0
  optimus: ^0.14.1
  mews_pedantic: ^0.4.1
  stream_transform: ^2.0.0
  flutter:
    sdk: flutter

  

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:

  uses-material-design: true