// definition of action types

// API calls
export const API_ERROR_CONFIGURATION = 'API_ERROR_CONFIGURATION';
export const API_ERROR_RATES = 'API_ERROR_RATES';
export const API_RECEIVED_CONFIGURATION = 'API_RECEIVED_CONFIGURATION';
export const API_RECEIVED_RATES = 'API_RECEIVED_RATES';
export const API_REQUESTED_CONFIGURATION = 'API_REQUESTED_CONFIGURATION';
export const API_REQUESTED_RATES = 'API_REQUESTED_RATES';

// UI
export const UI_CURRENCY_SELECT = 'UI_CURRENCY_SELECT';
export const UI_CURRENCY_DESELECT = 'UI_CURRENCY_DESELECT';
export const UI_CURRENCY_FILTER = 'UI_CURRENCY_FILTER';
