export const GET_CURRENCY_PAIRS_STARTED = 'GET_CURRENCY_PAIRS_STARTED';
export const GET_CURRENCY_PAIRS_SUCCESS = 'GET_CURRENCY_PAIRS_SUCCESS';
export const GET_CURRENCY_PAIRS_FAILURE = 'GET_CURRENCY_PAIRS_FAILURE';

export const GET_RATES_STARTED = 'GET_RATES_STARTED';
export const GET_RATES_SUCCESS = 'GET_RATES_SUCCESS';
export const GET_RATES_FAILURE = 'GET_RATES_FAILURE';

export const COMPUTE_TRENDS = 'COMPUTE_TRENDS';
export const SET_FILTER_PARAMS = 'SET_FILTER_PARAMS';
