export const GET_CONFIGURATION_SUCCESS = 'GET_CONFIGURATION_SUCCESS';
export const GET_RATE_SUCCESS = 'GET_RATE_SUCCESS';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const RESPONSE_ERROR = 'RESPONSE_ERROR';
export const FILTER = 'FILTER';
