export const FETCH_CONFIG_INIT = 'FETCH_CONFIG_INIT';
export const FETCH_CONFIG = 'FETCH_CONFIG';
export const FETCH_CONFIG_FAIL = 'FETCH_CONFIG_FAIL';
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const CHECK_CONFIG = 'CHECK_CONFIG';

export const FETCH_RATES_INIT = 'FETCH_RATES_INIT';
export const FETCH_RATES_FAIL = 'FETCH_RATES_FAIL';
export const UPDATE_RATES_SUCCESS = 'UPDATE_RATES_SUCCESS';
export const FETCH_RATES_RETRY = 'FETCH_RATES_RETRY';
export const SYNC_RATES = 'SYNC_RATES';

export const FILTER = 'FILTER';

export const RESET_FILTER = 'RESET_FILTER';
