export const FETCH_CONFIG_INIT = 'FETCH_CONFIG_INIT';
export const FETCH_CONFIG_FAIL = 'FETCH_CONFIG_FAIL';
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';

export const FETCH_RATES_INIT = 'FETCH_RATES_INIT';
export const FETCH_RATES_FAIL = 'FETCH_RATES_FAIL';
export const UPDATE_RATES_SUCCESS = 'UPDATE_RATES_SUCCESS';
export const FETCH_RATES_RETRY = 'FETCH_RATES_RETRY';
export const UPDATE_RATES = 'UPDATE_RATES';
