export const FETCH_PAIRS_START = 'FETCH_PAIRS_START'
export const FETCH_PAIRS_SUCCESS = 'FETCH_PAIRS_SUCCESS'
export const FETCH_PAIRS_FAILED = 'FETCH_PAIRS_FAILED'
export const UPDATE_PAIRS = 'UPDATE_PAIRS'

export const FETCH_RATES_START = 'FETCH_RATES_START'
export const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS'
export const FETCH_RATES_FAILED = 'FETCH_RATES_FAILED'
export const UPDATE_RATES = 'UPDATE_RATES'
