language: node_js
before_install:
  - cd Frontend
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn checkAll
  - yarn build
  - yarn test --coverage
after_script:
  - yarn collect-coverage
