// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'center': string;
  'falling': string;
  'flexContainer': string;
  'flexRow': string;
  'lds-circle': string;
  'ldsCircle': string;
  'passive': string;
  'rising': string;
  'shrink1': string;
  'shrink2': string;
  'stable': string;
}
export const cssExports: CssExports;
export default cssExports;
