export const mockMovie = {
  genres: [
    {
      id: 28,
      name: "Action",
    },
    {
      id: 878,
      name: "Science Fiction",
    },
  ],
  id: 603,
  origin_country: ["US"],
  overview:
    "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
  poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
  release_date: "1999-03-31",
  runtime: 136,
  tagline: "Believe the unbelievable.",
  title: "The Matrix",
  vote_average: 8.214,
  vote_count: 24751,
  credits: {
    cast: [
      {
        adult: false,
        gender: 2,
        id: 6384,
        known_for_department: "Acting",
        name: "Keanu Reeves",
        original_name: "Keanu Reeves",
        popularity: 103.843,
        profile_path: "/4D0PpNI0kmP58hgrwGC3wCjxhnm.jpg",
        cast_id: 34,
        character: "Neo",
        credit_id: "52fe425bc3a36847f80181c1",
        order: 0,
      },
      {
        adult: false,
        gender: 2,
        id: 2975,
        known_for_department: "Acting",
        name: "Laurence Fishburne",
        original_name: "Laurence Fishburne",
        popularity: 39.849,
        profile_path: "/iwx7h0AfWMm9K4sMmhru3ShSra.jpg",
        cast_id: 21,
        character: "Morpheus",
        credit_id: "52fe425bc3a36847f801818d",
        order: 1,
      },
      {
        adult: false,
        gender: 1,
        id: 530,
        known_for_department: "Acting",
        name: "Carrie-Anne Moss",
        original_name: "Carrie-Anne Moss",
        popularity: 32.73,
        profile_path: "/xD4jTA3KmVp5Rq3aHcymL9DUGjD.jpg",
        cast_id: 22,
        character: "Trinity",
        credit_id: "52fe425bc3a36847f8018191",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 1331,
        known_for_department: "Acting",
        name: "Hugo Weaving",
        original_name: "Hugo Weaving",
        popularity: 44.969,
        profile_path: "/t4ScpYIHlXVD41scEyiGdQDYflX.jpg",
        cast_id: 23,
        character: "Agent Smith",
        credit_id: "52fe425bc3a36847f8018195",
        order: 3,
      },
    ],
    crew: [
      {
        adult: false,
        gender: 1,
        id: 9340,
        known_for_department: "Writing",
        name: "Lana Wachowski",
        original_name: "Lana Wachowski",
        popularity: 24.415,
        profile_path: "/4nE4ttPQBuw1virOz0LYT08c1Vm.jpg",
        credit_id: "571756c4c3a3687bc70008e9",
        department: "Directing",
        job: "Director",
      },
      {
        adult: false,
        gender: 1,
        id: 9339,
        known_for_department: "Writing",
        name: "Lilly Wachowski",
        original_name: "Lilly Wachowski",
        popularity: 13.371,
        profile_path: "/rCScAjSpeKA19BLNR07MqNNeeTT.jpg",
        credit_id: "571756cfc3a3687c2c000a63",
        department: "Directing",
        job: "Director",
      },
    ],
  },
};
