import { MovieInformation } from '../../domain/interfaces/movie.interface.ts'

export const getInitialMovieInformation = (): MovieInformation => ({
    id: 0,
    title: '',
    overview: '',
    poster_path: '',
    release_date: '',
    genres: [],
    runtime: 0,
    vote_average: 0,
    vote_count: 0,
    budget: 0,
    revenue: 0,
    tagline: '',
    status: '',
    homepage: '',
    production_companies: [],
    production_countries: [],
    spoken_languages: [],
    video: false,
    adult: false,
    backdrop_path: '',
    belongs_to_collection: '',
    imdb_id: '',
    original_language: '',
    original_title: '',
    popularity: 0,
})
