export default {
  CURRENCY_LIST_DONE: 'CURRENCY_LIST_DONE',
  CURRENCY_LIST_FAILED: 'CURRENCY_LIST_FAILED',
  CURRENCY_LIST_FETCHING: 'CURRENCY_LIST_FETCHING',
  RATE_LIST_DONE: 'RATE_LIST_DONE',
  RATE_LIST_FAILED: 'RATE_LIST_FAILED',
  RATE_LIST_FETCHING: 'RATE_LIST_FETCHING',
  FILTER_SELECTED: 'FILTER_SELECTED',
}
