export const FETCH_RATES_REQUEST = 'FETCH_RATES_REQUES';
export const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS';
export const FETCH_RATES_FAILURE = 'FETCH_RATES_FAILURE'
export const HTTP_500_ERROR = 'HTTP_500_ERROR';
