export const mockGetMovieCollection = {
  id: 2344,
  name: "The Matrix Collection",
  overview:
    "The Matrix collection depicts a complex science fiction story incorporating many philosophical elements. Written and directed by the Wachowskis and produced by Joel Silver.",
  poster_path: "/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg",
  backdrop_path: "/bRm2DEgUiYciDw3myHuYFInD7la.jpg",
  parts: [
    {
      adult: false,
      backdrop_path: "/8K9qHeM6G6QjQN0C5XKFGvK5lzM.jpg",
      id: 603,
      title: "The Matrix",
      original_title: "The Matrix",
      overview:
        "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
      poster_path: "/p96dm7sCMn4VYAStA6siNz30G1r.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [28, 878],
      popularity: 20.4972,
      release_date: "1999-03-31",
      video: false,
      vote_average: 8.233,
      vote_count: 26796,
    },
    {
      adult: false,
      backdrop_path: "/96WHK0TiIslmM8rGVIejMtMtaPG.jpg",
      id: 604,
      title: "The Matrix Reloaded",
      original_title: "The Matrix Reloaded",
      overview:
        "The Resistance builds in numbers as humans are freed from the Matrix and brought to the city of Zion. Neo discovers his superpowers, including the ability to see the code inside the Matrix. With machine sentinels digging to Zion in 72 hours, Neo, Morpheus and Trinity must find the Keymaker to ultimately reach the Source.",
      poster_path: "/9TGHDvWrqKBzwDxDodHYXEmOE6J.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [12, 28, 53, 878],
      popularity: 10.1559,
      release_date: "2003-05-15",
      video: false,
      vote_average: 7.1,
      vote_count: 11443,
    },
    {
      adult: false,
      backdrop_path: "/533xAMhhVyjTy8hwMUFEt5TuDfR.jpg",
      id: 605,
      title: "The Matrix Revolutions",
      original_title: "The Matrix Revolutions",
      overview:
        "The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.",
      poster_path: "/t1wm4PgOQ8e4z1C6tk1yDNrps4T.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [12, 28, 53, 878],
      popularity: 12.207,
      release_date: "2003-11-05",
      video: false,
      vote_average: 6.747,
      vote_count: 10333,
    },
    {
      adult: false,
      backdrop_path: "/k0Cuybu9ECuc47ODlHcIP8TJCZi.jpg",
      id: 624860,
      title: "The Matrix Resurrections",
      original_title: "The Matrix Resurrections",
      overview:
        "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
      poster_path: "/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [878, 28, 12],
      popularity: 9.6759,
      release_date: "2021-12-16",
      video: false,
      vote_average: 6.365,
      vote_count: 6110,
    },
  ],
};