name: Build

on:
  [push, pull_request]
    branches: [ "main", "master" ]
    paths:
      - 'ExchangeRateProvider/jobs/Backend/ExchangeRateUpdater/**'

jobs:
  build:
    defaults:
      run:
        working-directory: ExchangeRateUpdater

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
