import { ReactNode } from "react";
import type { Metadata } from "next";
import { LOCALES } from "@/util/constants";
import { notFound } from "next/navigation";
import { Providers } from "../_components/providers";

type Params = { locale: string };
type Props = { children: ReactNode; params: Params };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "manifest.json",
};

export default function RootLayout({ children, params: { locale } }: Props) {
  if (!LOCALES.includes(locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body>
        <Providers locale={locale}>{children}</Providers>
      </body>
    </html>
  );
}
