export const FETCH_CONFIGURATION_REQUEST = 'FETCH_CONFIGURATION_REQUEST'
export const FETCH_CONFIGURATION_SUCCESS = 'FETCH_CONFIGURATION_SUCCESS'
export const FETCH_CONFIGURATION_FAILURE = 'FETCH_CONFIGURATION_FAILURE'