export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const FETCH_RATES = 'FETCH_RATES';
export const FETCHING_RATES_ERROR = 'FETCHING_RATES_ERROR';
export const SET_FILTER_VALUE = 'SET_FILTER_VALUE';
