/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthcallbackRouteImport } from './routes/authcallback'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthMoviesRouteImport } from './routes/_auth.movies'
import { Route as AuthMoviedetailsMovieIdRouteImport } from './routes/_auth.moviedetails.$movieId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthcallbackRoute = AuthcallbackRouteImport.update({
  id: '/authcallback',
  path: '/authcallback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMoviesRoute = AuthMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMoviedetailsMovieIdRoute = AuthMoviedetailsMovieIdRouteImport.update({
  id: '/moviedetails/$movieId',
  path: '/moviedetails/$movieId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authcallback': typeof AuthcallbackRoute
  '/login': typeof LoginRoute
  '/movies': typeof AuthMoviesRoute
  '/moviedetails/$movieId': typeof AuthMoviedetailsMovieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authcallback': typeof AuthcallbackRoute
  '/login': typeof LoginRoute
  '/movies': typeof AuthMoviesRoute
  '/moviedetails/$movieId': typeof AuthMoviedetailsMovieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/authcallback': typeof AuthcallbackRoute
  '/login': typeof LoginRoute
  '/_auth/movies': typeof AuthMoviesRoute
  '/_auth/moviedetails/$movieId': typeof AuthMoviedetailsMovieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authcallback'
    | '/login'
    | '/movies'
    | '/moviedetails/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authcallback' | '/login' | '/movies' | '/moviedetails/$movieId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/authcallback'
    | '/login'
    | '/_auth/movies'
    | '/_auth/moviedetails/$movieId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthcallbackRoute: typeof AuthcallbackRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authcallback': {
      id: '/authcallback'
      path: '/authcallback'
      fullPath: '/authcallback'
      preLoaderRoute: typeof AuthcallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/movies': {
      id: '/_auth/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof AuthMoviesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/moviedetails/$movieId': {
      id: '/_auth/moviedetails/$movieId'
      path: '/moviedetails/$movieId'
      fullPath: '/moviedetails/$movieId'
      preLoaderRoute: typeof AuthMoviedetailsMovieIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthMoviesRoute: typeof AuthMoviesRoute
  AuthMoviedetailsMovieIdRoute: typeof AuthMoviedetailsMovieIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMoviesRoute: AuthMoviesRoute,
  AuthMoviedetailsMovieIdRoute: AuthMoviedetailsMovieIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthcallbackRoute: AuthcallbackRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
