export const IMAGE_PLACEHOLDER_URL =
  "data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAfQAAABLCAYAAACGPXWeAAABBElEQVR42u3VQREAAAQAMJLL5qGXHM5WYtk9FQDAaSl0ABA6ACB0AEDoAIDQAUDoAIDQAQChAwBCBwChAwBCBwCEDgAIHQCEDgAIHQAQOgAgdAAQOgAgdABA6ACA0AFA6ACA0AEAoQMAQgcAoQMAQgcAhA4ACB0AhA4ACB0AEDoAIHQAEDoAIHQAQOgAgNABQOgAgNABAKEDAEIHAKELHQCEDgAIHQAQOgAgdAAQOgAgdABA6ACA0AFA6ACA0AEAoQMAQgcAoQMAQgcAhA4ACB0AhA4ACB0AEDoAIHQAEDoAIHQAQOgAgNABQOgAgNABAKEDAEIHAKEDAEIHAIQOAAgdAJ5Zv3PQTkffvswAAAAASUVORK5CYII=";

export const getImageUrl = (size: number, url: string) => {
  if (url.startsWith("/")) {
    return `${process.env.NEXT_PUBLIC_MOVIE_DB_API_IMAGE_BASE_URL}/w${size}${url}`;
  }

  return `${process.env.NEXT_PUBLIC_MOVIE_DB_API_IMAGE_BASE_URL}/w${size}/${url}`;
};
