const DirectoryActionTypes = {
  FETCH_TOP_RATED_MOVIES_PENDING: "FETCH_TOP_RATED_MOVIES_PENDING",
  FETCH_TOP_RATED_MOVIES_SUCCESS: "FETCH_TOP_RATED_MOVIES_SUCCESS",
  FETCH_TOP_RATED_MOVIES_ERROR: "FETCH_TOP_RATED_MOVIES_ERROR"
};

export default DirectoryActionTypes;
