//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class kurzy {
    
    private kurzyTabulka[] tabulkaField;
    
    private string bankaField;
    
    private string datumField;
    
    private string poradiField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tabulka", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public kurzyTabulka[] tabulka {
        get {
            return this.tabulkaField;
        }
        set {
            this.tabulkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string banka {
        get {
            return this.bankaField;
        }
        set {
            this.bankaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string poradi {
        get {
            return this.poradiField;
        }
        set {
            this.poradiField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class kurzyTabulka {
    
    private kurzyTabulkaRadek[] radekField;
    
    private string typField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("radek", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public kurzyTabulkaRadek[] radek {
        get {
            return this.radekField;
        }
        set {
            this.radekField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string typ {
        get {
            return this.typField;
        }
        set {
            this.typField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class kurzyTabulkaRadek {
    
    private string kodField;
    
    private string menaField;
    
    private string mnozstviField;
    
    private string kurzField;
    
    private string zemeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kod {
        get {
            return this.kodField;
        }
        set {
            this.kodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mena {
        get {
            return this.menaField;
        }
        set {
            this.menaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mnozstvi {
        get {
            return this.mnozstviField;
        }
        set {
            this.mnozstviField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kurz {
        get {
            return this.kurzField;
        }
        set {
            this.kurzField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string zeme {
        get {
            return this.zemeField;
        }
        set {
            this.zemeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private kurzy[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("kurzy")]
    public kurzy[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
