const SearchMovieActionTypes = {
  PERFORM_SEARCH_PENDING: "PERFORM_SEARCH_PENDING",
  PERFORM_SEARCH_SUCCESS: "PERFORM_SEARCH_SUCCESS",
  PERFORM_SEARCH_ERROR: "PERFORM_SEARCH_ERROR"
};

export default SearchMovieActionTypes;
