name: movies
description: Flutter task for Mews

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  entry: ^0.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
  mews_pedantic: ^0.10.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  sliver_tools: ^0.2.8


dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
