//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeRateUpdater {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeRateUpdater.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currencies should be set.
        /// </summary>
        internal static string CurrenciesShouldBeSet {
            get {
                return ResourceManager.GetString("CurrenciesShouldBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currencies should be set for getting exchange rates.
        /// </summary>
        internal static string CurrenciesShouldBeSetForGettingER {
            get {
                return ResourceManager.GetString("CurrenciesShouldBeSetForGettingER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency should be set.
        /// </summary>
        internal static string CurrencyShouldBeSet {
            get {
                return ResourceManager.GetString("CurrencyShouldBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate item in exchange rate list.
        /// </summary>
        internal static string DuplicateInExRateList {
            get {
                return ResourceManager.GetString("DuplicateInExRateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code of currency is empty.
        /// </summary>
        internal static string EmptyCurrencyCode {
            get {
                return ResourceManager.GetString("EmptyCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency code (three-letter) must be in accordance with the ISO 4217 of the currency..
        /// </summary>
        internal static string ErrorCurrencyCode {
            get {
                return ResourceManager.GetString("ErrorCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving exchange rates.
        /// </summary>
        internal static string ErrorWhileRetrievingER {
            get {
                return ResourceManager.GetString("ErrorWhileRetrievingER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rate item is empty.
        /// </summary>
        internal static string ExchangeRateItemIsEmpty {
            get {
                return ResourceManager.GetString("ExchangeRateItemIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchange rates.
        /// </summary>
        internal static string exchangeRates {
            get {
                return ResourceManager.GetString("exchangeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for closing application.
        /// </summary>
        internal static string ForClosingApp {
            get {
                return ResourceManager.GetString("ForClosingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CzechNationalBankProvider - internal error.
        /// </summary>
        internal static string InternalErrorProviderCZK {
            get {
                return ResourceManager.GetString("InternalErrorProviderCZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExchangeRateLablProvider - internal error.
        /// </summary>
        internal static string InternalErrorProviderExRateLab {
            get {
                return ResourceManager.GetString("InternalErrorProviderExRateLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source parsing error.
        /// </summary>
        internal static string ParsingError {
            get {
                return ResourceManager.GetString("ParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key for updating or type.
        /// </summary>
        internal static string PressAnyKeyOr {
            get {
                return ResourceManager.GetString("PressAnyKeyOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from provider source is empty.
        /// </summary>
        internal static string SourceDataIsEmpty {
            get {
                return ResourceManager.GetString("SourceDataIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully retrieved.
        /// </summary>
        internal static string SuccessfullyRetrieved {
            get {
                return ResourceManager.GetString("SuccessfullyRetrieved", resourceCulture);
            }
        }
    }
}
