export const FETCH_CURRENCY_LIST = 'FETCH_CURRENCY_LIST';
export const FETCH_CURRENCY_LIST_SUCCESS = 'FETCH_CURRENCY_LIST_SUCCESS';
export const FETCH_CURRENCY_LIST_ERROR = 'FETCH_CURRENCY_LIST_ERROR';
export const UPDATE_CURRENCY_RATES = 'UPDATE_CURRENCY_RATES';
export const UPDATE_CURRENCY_RATES_SUCCESS = 'UPDATE_CURRENCY_RATES_SUCCESS';
export const UPDATE_CURRENCY_RATES_ERROR = 'UPDATE_CURRENCY_RATES_ERROR';
export const  SET_FILTER = 'SET_FILTER';

