using System;

namespace ExchangeRateUpdater.Entities.Xml
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "kurzy", IsNullable = false)]
    public class CnbXmlRatesDocument
    {

        private CnbXmlRatesTable _ratesTableField;

        private string _bankField;

        private string _dateField;

        private string poradiField;

        /// <remarks/>
        [XmlElementAttribute("tabulka", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CnbXmlRatesTable RatesTable
        {
            get { return _ratesTableField; }
            set { _ratesTableField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute("banka")]
        public string Bank
        {
            get { return _bankField; }
            set { _bankField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute("datum")]
        public string Date
        {
            get { return _dateField; }
            set { _dateField = value; }
        }
    }
}