// flow-typed signature: 5e1308e18aa5c0286b851ee762dc432c
// flow-typed version: <<STUB>>/axios-retry_v^3.1.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axios-retry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axios-retry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axios-retry/es/index' {
  declare module.exports: any;
}

declare module 'axios-retry/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axios-retry/es/index.js' {
  declare module.exports: $Exports<'axios-retry/es/index'>;
}
declare module 'axios-retry/index' {
  declare module.exports: $Exports<'axios-retry'>;
}
declare module 'axios-retry/index.js' {
  declare module.exports: $Exports<'axios-retry'>;
}
declare module 'axios-retry/lib/index.js' {
  declare module.exports: $Exports<'axios-retry/lib/index'>;
}
