// flow-typed signature: eb846396728c782e8364d575533a18e6
// flow-typed version: <<STUB>>/jest-mock-axios_v^2.1.11/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-mock-axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-mock-axios' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-mock-axios/dist/index' {
  declare module.exports: any;
}

declare module 'jest-mock-axios/jest.config' {
  declare module.exports: any;
}

declare module 'jest-mock-axios/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-mock-axios/dist/index.js' {
  declare module.exports: $Exports<'jest-mock-axios/dist/index'>;
}
declare module 'jest-mock-axios/jest.config.js' {
  declare module.exports: $Exports<'jest-mock-axios/jest.config'>;
}
declare module 'jest-mock-axios/webpack.config.js' {
  declare module.exports: $Exports<'jest-mock-axios/webpack.config'>;
}
