// flow-typed signature: 697453cd630bd391b89940e0cc20eb16
// flow-typed version: <<STUB>>/react-icons_v^3.0.5/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-icons/fa/index' {
  declare module.exports: any;
}

declare module 'react-icons/fi/index' {
  declare module.exports: any;
}

declare module 'react-icons/go/index' {
  declare module.exports: any;
}

declare module 'react-icons/io/index' {
  declare module.exports: any;
}

declare module 'react-icons/lib/iconBase' {
  declare module.exports: any;
}

declare module 'react-icons/lib/iconContext' {
  declare module.exports: any;
}

declare module 'react-icons/lib/iconsManifest' {
  declare module.exports: any;
}

declare module 'react-icons/lib/index' {
  declare module.exports: any;
}

declare module 'react-icons/md/index' {
  declare module.exports: any;
}

declare module 'react-icons/plugin/defaultImportConverter' {
  declare module.exports: any;
}

declare module 'react-icons/src/icons/index' {
  declare module.exports: any;
}

declare module 'react-icons/ti/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-icons/fa/index.js' {
  declare module.exports: $Exports<'react-icons/fa/index'>;
}
declare module 'react-icons/fi/index.js' {
  declare module.exports: $Exports<'react-icons/fi/index'>;
}
declare module 'react-icons/go/index.js' {
  declare module.exports: $Exports<'react-icons/go/index'>;
}
declare module 'react-icons/io/index.js' {
  declare module.exports: $Exports<'react-icons/io/index'>;
}
declare module 'react-icons/lib/iconBase.js' {
  declare module.exports: $Exports<'react-icons/lib/iconBase'>;
}
declare module 'react-icons/lib/iconContext.js' {
  declare module.exports: $Exports<'react-icons/lib/iconContext'>;
}
declare module 'react-icons/lib/iconsManifest.js' {
  declare module.exports: $Exports<'react-icons/lib/iconsManifest'>;
}
declare module 'react-icons/lib/index.js' {
  declare module.exports: $Exports<'react-icons/lib/index'>;
}
declare module 'react-icons/md/index.js' {
  declare module.exports: $Exports<'react-icons/md/index'>;
}
declare module 'react-icons/plugin/defaultImportConverter.js' {
  declare module.exports: $Exports<'react-icons/plugin/defaultImportConverter'>;
}
declare module 'react-icons/src/icons/index.js' {
  declare module.exports: $Exports<'react-icons/src/icons/index'>;
}
declare module 'react-icons/ti/index.js' {
  declare module.exports: $Exports<'react-icons/ti/index'>;
}
