// flow-typed signature: 41f2ae824b928bc47221e569ccee1f88
// flow-typed version: <<STUB>>/styled-componets_v3.4.5/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-componets'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "styled-componets" {
  declare module.exports: any;
}
