name: dotnet-build-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      run: git config --global core.autocrlf true
    - uses: actions/checkout@v2
    - name: Restore dependencies
      working-directory: jobs/Backend/Task/
      run: dotnet restore
    - name: Build
      working-directory: jobs/Backend/Task/
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: jobs/Backend/Task/
      run: dotnet test --configuration Release --no-build --verbosity normal
