name: dotnet-build-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      run: git config --global core.autocrlf true
    - name: List
      run: ls
    - name: Restore dependencies
      run: |
          ls
          cd jobs/Backend/Task/
          dotnet restore
    - name: Build
      run: |
          cd jobs/Backend/Task/
          dotnet build --configuration Release --no-restore
    - name: Test
      run: |
          cd jobs/Backend/Task/
          dotnet test --configuration Release --no-build --verbosity normal
