name: ExchangeRateUpdater Flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
      - 'ExchangeRateProvider/jobs/Backend/ExchangeRateUpdater/**'

jobs:
  myJob:
    name: ExchangeRateUpdater CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/ExchangeRateUpdater
