name: movie_finder
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^5.1.1
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/config/config.json


























